apiVersion: v1
kind: PersistentVolume
metadata:
  name: deployment-tests-logs-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: $PWD/src/deployment-tests
    type: Directory
  claimRef:
    namespace: deployment-tests
    name: deployment-tests-logs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deployment-tests-logs-pvc
  namespace: deployment-tests
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
