apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: deployment-demo-rollout
  namespace: poc-rollouts
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment-demo
      namespace: poc-rollouts
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-demo
    scaleDown: onsuccess
  strategy:
    blueGreen:
      activeService: deployment-demo
      previewService: deployment-demo-preview
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-demo-preview
  namespace: poc-rollouts
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: deployment-demo
    namespace: poc-rollouts
