apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  namespace: poc-rollouts
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: deployment-demo
      namespace: poc-rollouts
  template:
    metadata:
      labels:
        app: deployment-demo
        namespace: poc-rollouts
    spec:
      containers:
        - name: deployment-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-demo
  namespace: poc-rollouts
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: deployment-demo
    namespace: poc-rollouts
